spring:
  security:
    oauth2:
      client:
        registration:
          github:
            clientId: 819b0486a89e9839768b
            clientSecret: 180b944fe0db7f9427241004448be2aa94f5afea
            accessTokenUri: https://github.com/login/oauth/access_token
            userAuthorizationUri: https://github.com/login/oauth/authorize
            clientAuthenticationScheme: form
            resource:
              user-info-uri: https://api.github.com/user
              prefer-token-info: false


#security:
#  oauth2:
#    client:
#      clientId: 819b0486a89e9839768b
#      clientSecret: 180b944fe0db7f9427241004448be2aa94f5afea
#      accessTokenUri: https://github.com/login/oauth/access_token
#      userAuthorizationUri: https://github.com/login/oauth/authorize
#      clientAuthenticationScheme: form
#    resource:
#      user-info-uri: https://api.github.com/user
#      prefer-token-info: false

#spring:
#  security:
#    oauth2:
#      client:
#        registration:
#          facebook:
#            clientId: myID
#            clientSecret: mySecret
#            accessTokenUri: https://graph.facebook.com/oauth/access_token
#            userAuthorizationUri: https://www.facebook.com/dialog/oauth
#            tokenName: oauth_token
#            authenticationScheme: query
#            clientAuthenticationScheme: form
#            resource:
#              userInfoUri: https://graph.facebook.com/me

